BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON

ALTER TABLE dbo.PaymentAgentSetupBradesco ADD
	useStoreOrderReference bit NOT NULL CONSTRAINT DF_PaymentAgentSetupBradesco_useStoreOrderReference DEFAULT 0
	
ALTER TABLE dbo.HandshakeConfiguration ADD
	validateItemsTotal bit NOT NULL CONSTRAINT DF_HandshakeConfiguration_validateItemsTotal DEFAULT 0
	
UPDATE _DBVERSION SET dbversion = 3
GO

IF @@ERROR <> 0
BEGIN
	PRINT(@@ERROR)
	ROLLBACK
END
ELSE
	PRINT('OK')
	COMMIT