//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 

namespace SuperPag.Helper.Xml.Response
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class response
    {

        private responseOrders ordersField;

        /// <remarks/>
        public responseOrders orders
        {
            get
            {
                return this.ordersField;
            }
            set
            {
                this.ordersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class responseOrders
    {

        private responseOrdersOrder[] orderField;

        private ulong batchIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("order")]
        public responseOrdersOrder[] order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong batchId
        {
            get
            {
                return this.batchIdField;
            }
            set
            {
                this.batchIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class responseOrdersOrder
    {

        private responseOrdersOrderPayment[] paymentsField;

        private ulong idField;

        private string referenceField;

        private ulong totalField;

        private byte statusField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("payment", IsNullable = false)]
        public responseOrdersOrderPayment[] payments
        {
            get
            {
                return this.paymentsField;
            }
            set
            {
                this.paymentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class responseOrdersOrderPayment
    {

        private responseOrdersOrderPaymentInstallment[] installmentsField;

        private byte statusField;

        private ushort formField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("installment", IsNullable = false)]
        public responseOrdersOrderPaymentInstallment[] installments
        {
            get
            {
                return this.installmentsField;
            }
            set
            {
                this.installmentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort form
        {
            get
            {
                return this.formField;
            }
            set
            {
                this.formField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class responseOrdersOrderPaymentInstallment
    {

        private responseOrdersOrderPaymentInstallmentPaymentFormDetail paymentFormDetailField;

        private ulong numberField;

        private byte statusField;

        private System.DateTime dateField;

        private bool dateFieldSpecified;

        private System.DateTime paymentDateField;

        private bool paymentDateFieldSpecified;

        /// <remarks/>
        public responseOrdersOrderPaymentInstallmentPaymentFormDetail paymentFormDetail
        {
            get
            {
                return this.paymentFormDetailField;
            }
            set
            {
                this.paymentFormDetailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified
        {
            get
            {
                return this.dateFieldSpecified;
            }
            set
            {
                this.dateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime paymentDate
        {
            get
            {
                return this.paymentDateField;
            }
            set
            {
                this.paymentDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentDateSpecified
        {
            get
            {
                return this.paymentDateFieldSpecified;
            }
            set
            {
                this.paymentDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class responseOrdersOrderPaymentInstallmentPaymentFormDetail
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("boletoInformation", typeof(responseOrdersOrderPaymentInstallmentPaymentFormDetailBoletoInformation))]
        [System.Xml.Serialization.XmlElementAttribute("creditCardInformation", typeof(responseOrdersOrderPaymentInstallmentPaymentFormDetailCreditCardInformation))]
        [System.Xml.Serialization.XmlElementAttribute("ContaCorrenteInformation", typeof(responseOrdersOrderPaymentInstallmentPaymentFormDetailContaCorrenteInformation))]
        [System.Xml.Serialization.XmlElementAttribute("boletoInformationIPTE", typeof(responseOrdersOrderPaymentInstallmentPaymentFormDetailBoletoInformationIPTE))]
        [System.Xml.Serialization.XmlElementAttribute("DebitoContaCorrenteInformation", typeof(responseOrdersOrderPaymentInstallmentPaymentFormDetailDebitoContaCorrenteInformation))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class responseOrdersOrderPaymentInstallmentPaymentFormDetailBoletoInformationIPTE
    {
        private string paymentAttemptIdField;

        public string PaymentAttemptId
        {
            get { return paymentAttemptIdField; }
            set { paymentAttemptIdField = value; }
        }        
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class responseOrdersOrderPaymentInstallmentPaymentFormDetailBoletoInformation
    {

        private string numberField;

        private string urlField;

        private string typingLineField;

        private ulong paidValueField;

        private bool paidValueFieldSpecified;

        /// <remarks/>
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public string typingLine
        {
            get
            {
                return this.typingLineField;
            }
            set
            {
                this.typingLineField = value;
            }
        }

        /// <remarks/>
        public ulong paidValue
        {
            get
            {
                return this.paidValueField;
            }
            set
            {
                this.paidValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paidValueSpecified
        {
            get
            {
                return this.paidValueFieldSpecified;
            }
            set
            {
                this.paidValueFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class responseOrdersOrderPaymentInstallmentPaymentFormDetailCreditCardInformation
    {

        private string transactionIdField;

        private string authorizationIdField;

        private returnCode returnCodeField;

        private string acquirerReturnCodeField;

        private string acquirerReturnMessageField;

        /// <remarks/>
        public string transactionId
        {
            get
            {
                return this.transactionIdField;
            }
            set
            {
                this.transactionIdField = value;
            }
        }

        /// <remarks/>
        public string authorizationId
        {
            get
            {
                return this.authorizationIdField;
            }
            set
            {
                this.authorizationIdField = value;
            }
        }

        /// <remarks/>
        public returnCode returnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }

        /// <remarks/>
        public string acquirerReturnCode
        {
            get
            {
                return this.acquirerReturnCodeField;
            }
            set
            {
                this.acquirerReturnCodeField = value;
            }
        }

        /// <remarks/>
        public string acquirerReturnMessage
        {
            get
            {
                return this.acquirerReturnMessageField;
            }
            set
            {
                this.acquirerReturnMessageField = value;
            }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class responseOrdersOrderPaymentInstallmentPaymentFormDetailContaCorrenteInformation
    {        

        private string ReturnMessageField;
        private string paymentAttemptIdField;

        public string PaymentAttemptId
        {
            get { return paymentAttemptIdField; }
            set { paymentAttemptIdField = value; }
        }
        /// <remarks/>
        public string ReturnMessage
        {
            get
            {
                return this.ReturnMessageField;
            }
            set
            {
                this.ReturnMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class responseOrdersOrderPaymentInstallmentPaymentFormDetailDebitoContaCorrenteInformation
    {
        private int StatusField;        
        private DateTime DataVencimentoField;        
        private decimal ValorAgendadoField;    
        private int NumInstituicaoField;       
        private string OcorrenciaField;        
        private DateTime DataProcessamentoField;        

        public int Status
        {
            get { return StatusField; }
            set { StatusField = value; }
        }
        public DateTime DataVencimento
        {
            get { return DataVencimentoField; }
            set { DataVencimentoField = value; }
        }
        public decimal ValorAgendado
        {
            get { return ValorAgendadoField; }
            set { ValorAgendadoField = value; }
        }
        public int NumInstituicao
        {
            get { return NumInstituicaoField; }
            set { NumInstituicaoField = value; }
        }
        public string Ocorrencia
        {
            get { return OcorrenciaField; }
            set { OcorrenciaField = value; }
        }
        public DateTime DataProcessamento
        {
            get { return DataProcessamentoField; }
            set { DataProcessamentoField = value; }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    public enum returnCode
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }
}
