//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace SuperPag.Agents.KomerciWS.Messages
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class AUTHORIZATION
    {

        /// <remarks/>
        public string CODRET;

        /// <remarks/>
        public string MSGRET;

        /// <remarks/>
        public string NUMPEDIDO;

        /// <remarks/>
        public string DATA;

        /// <remarks/>
        public string NUMAUTOR;

        /// <remarks/>
        public string NUMCV;

        /// <remarks/>
        public string NUMAUTENT;

        /// <remarks/>
        public string NUMSQN;

        /// <remarks/>
        public string ORIGEM_BIN;

        /// <remarks/>
        public string CONFCODRET;

        /// <remarks/>
        public string CONFMSGRET;

        /// <remarks/>
        public string IATA;

        /// <remarks/>
        public string DISTRIBUIDOR;
    }
}
