//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Xml;
using System.IO;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 

namespace EasyPag.SuperPagWS.Legacy
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class PEDIDO
    {

        private PEDIDOCLIENTES_INTERNET cLIENTES_INTERNETField;

        private PEDIDOENDERECO_ENTREGA_PEDIDO eNDERECO_ENTREGA_PEDIDOField;

        private PEDIDOCLIENTES_INTERNET_PEDIDO cLIENTES_INTERNET_PEDIDOField;

        /// <remarks/>
        public PEDIDOCLIENTES_INTERNET CLIENTES_INTERNET
        {
            get
            {
                return this.cLIENTES_INTERNETField;
            }
            set
            {
                this.cLIENTES_INTERNETField = value;
            }
        }

        /// <remarks/>
        public PEDIDOENDERECO_ENTREGA_PEDIDO ENDERECO_ENTREGA_PEDIDO
        {
            get
            {
                return this.eNDERECO_ENTREGA_PEDIDOField;
            }
            set
            {
                this.eNDERECO_ENTREGA_PEDIDOField = value;
            }
        }

        /// <remarks/>
        public PEDIDOCLIENTES_INTERNET_PEDIDO CLIENTES_INTERNET_PEDIDO
        {
            get
            {
                return this.cLIENTES_INTERNET_PEDIDOField;
            }
            set
            {
                this.cLIENTES_INTERNET_PEDIDOField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PEDIDOCLIENTES_INTERNET
    {

        private ulong sTR_CPFField;

        private long iNT_NUMERO_PEDIDOField;

        private ulong sTR_TELEFONEField;

        private uint sTR_CEPField;

        private string dAT_NASCIMENTOField;

        private string sTR_NOME_CLIENTEField;

        private string sTR_SEXOField;

        private string sTR_ESTADO_CIVILField;

        private string sTR_PROFISSAOField;

        private string sTR_LOGRADOUROField;

        private string sTR_ENDERECOField;

        private string sTR_NUMERO_ENDERECOField;

        private string sTR_COMPLEMENTO_ENDERECOField;

        private string sTR_BAIRROField;

        private string sTR_EMAILField;

        private string sTR_CIDADEField;

        private string sTR_ESTADOField;

        private string sTR_RECEBER_EMAILField;

        private string sTR_FAXField;

        private string sTR_PAISField;

        private string sTR_GERA_CAPITALIZACAOField;

        private string sTR_INSCRICAOField;

        private string sTR_CPF_RESPONSAVELField;

        private string sTR_NOME_RESPONSAVELField;

        private string sTR_CELULARField;

        /// <remarks/>
        public ulong STR_CPF
        {
            get
            {
                return this.sTR_CPFField;
            }
            set
            {
                this.sTR_CPFField = value;
            }
        }

        /// <remarks/>
        public long INT_NUMERO_PEDIDO
        {
            get
            {
                return this.iNT_NUMERO_PEDIDOField;
            }
            set
            {
                this.iNT_NUMERO_PEDIDOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElement(IsNullable = true)]
        public string STR_NOME_CLIENTE
        {
            get
            {
                return this.sTR_NOME_CLIENTEField;
            }
            set
            {
                this.sTR_NOME_CLIENTEField = value;
            }
        }

        /// <remarks/>
        public string DAT_NASCIMENTO
        {
            get
            {
                return this.dAT_NASCIMENTOField;
            }
            set
            {
                this.dAT_NASCIMENTOField = value;
            }
        }

        /// <remarks/>
        public string STR_SEXO
        {
            get
            {
                return this.sTR_SEXOField;
            }
            set
            {
                this.sTR_SEXOField = value;
            }
        }

        /// <remarks/>
        public uint STR_CEP
        {
            get
            {
                return this.sTR_CEPField;
            }
            set
            {
                this.sTR_CEPField = value;
            }
        }

        /// <remarks/>
        public string STR_ESTADO_CIVIL
        {
            get
            {
                return this.sTR_ESTADO_CIVILField;
            }
            set
            {
                this.sTR_ESTADO_CIVILField = value;
            }
        }

        /// <remarks/>
        public string STR_PROFISSAO
        {
            get
            {
                return this.sTR_PROFISSAOField;
            }
            set
            {
                this.sTR_PROFISSAOField = value;
            }
        }

        /// <remarks/>
        public ulong STR_TELEFONE
        {
            get
            {
                return this.sTR_TELEFONEField;
            }
            set
            {
                this.sTR_TELEFONEField = value;
            }
        }

        /// <remarks/>
        public string STR_LOGRADOURO
        {
            get
            {
                return this.sTR_LOGRADOUROField;
            }
            set
            {
                this.sTR_LOGRADOUROField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElement(IsNullable = true)]
        public string STR_ENDERECO
        {
            get
            {
                return this.sTR_ENDERECOField;
            }
            set
            {
                this.sTR_ENDERECOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElement(IsNullable = true)]
        public string STR_NUMERO_ENDERECO
        {
            get
            {
                return this.sTR_NUMERO_ENDERECOField;
            }
            set
            {
                this.sTR_NUMERO_ENDERECOField = value;
            }
        }

        /// <remarks/>
        public string STR_COMPLEMENTO_ENDERECO
        {
            get
            {
                return this.sTR_COMPLEMENTO_ENDERECOField;
            }
            set
            {
                this.sTR_COMPLEMENTO_ENDERECOField = value;
            }
        }

        /// <remarks/>
        public string STR_BAIRRO
        {
            get
            {
                return this.sTR_BAIRROField;
            }
            set
            {
                this.sTR_BAIRROField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElement(IsNullable = true)]
        public string STR_EMAIL
        {
            get
            {
                return this.sTR_EMAILField;
            }
            set
            {
                this.sTR_EMAILField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElement(IsNullable = true)]
        public string STR_CIDADE
        {
            get
            {
                return this.sTR_CIDADEField;
            }
            set
            {
                this.sTR_CIDADEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElement(IsNullable = true)]
        public string STR_ESTADO
        {
            get
            {
                return this.sTR_ESTADOField;
            }
            set
            {
                this.sTR_ESTADOField = value;
            }
        }

        /// <remarks/>
        public string STR_RECEBER_EMAIL
        {
            get
            {
                return this.sTR_RECEBER_EMAILField;
            }
            set
            {
                this.sTR_RECEBER_EMAILField = value;
            }
        }

        /// <remarks/>
        public string STR_FAX
        {
            get
            {
                return this.sTR_FAXField;
            }
            set
            {
                this.sTR_FAXField = value;
            }
        }

        /// <remarks/>
        public string STR_PAIS
        {
            get
            {
                return this.sTR_PAISField;
            }
            set
            {
                this.sTR_PAISField = value;
            }
        }

        /// <remarks/>
        public string STR_GERA_CAPITALIZACAO
        {
            get
            {
                return this.sTR_GERA_CAPITALIZACAOField;
            }
            set
            {
                this.sTR_GERA_CAPITALIZACAOField = value;
            }
        }

        /// <remarks/>
        public string STR_INSCRICAO
        {
            get
            {
                return this.sTR_INSCRICAOField;
            }
            set
            {
                this.sTR_INSCRICAOField = value;
            }
        }

        /// <remarks/>
        public string STR_CPF_RESPONSAVEL
        {
            get
            {
                return this.sTR_CPF_RESPONSAVELField;
            }
            set
            {
                this.sTR_CPF_RESPONSAVELField = value;
            }
        }

        /// <remarks/>
        public string STR_NOME_RESPONSAVEL
        {
            get
            {
                return this.sTR_NOME_RESPONSAVELField;
            }
            set
            {
                this.sTR_NOME_RESPONSAVELField = value;
            }
        }

        /// <remarks/>
        public string STR_CELULAR
        {
            get
            {
                return this.sTR_CELULARField;
            }
            set
            {
                this.sTR_CELULARField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PEDIDOENDERECO_ENTREGA_PEDIDO
    {

        private ulong sTR_CPFField;

        private long iNT_NUMERO_PEDIDOField;

        private ulong sTR_TELEFONE_PEDIDOField;

        private uint sTR_CEP_ENTREGA_PEDIDOField;

        private byte iNT_CODIGO_USUARIOField;

        private System.DateTime dAT_ATUALIZACAOField;

        private string sTR_RESPONSAVEL_PEDIDOField;

        private string sTR_LOGRADOURO_ENTREGA_PEDIDOField;

        private string sTR_ENDERECO_ENTREGA_PEDIDOField;

        private string sTR_NUMERO_ENDERECO_ENTREGA_PEDIDOField;

        private string sTR_COMPLEMENTO_ENDERECO_ENTREGA_PEDIDOField;

        private string sTR_BAIRRO_ENTREGA_PEDIDOField;

        private string sTR_CIDADE_ENTREGA_PEDIDOField;

        private string sTR_ESTADO_ENTREGA_PEDIDOField;

        private string sTR_PAIS_ENTREGA_PEDIDOField;

        /// <remarks/>
        public ulong STR_CPF
        {
            get
            {
                return this.sTR_CPFField;
            }
            set
            {
                this.sTR_CPFField = value;
            }
        }

        /// <remarks/>
        public long INT_NUMERO_PEDIDO
        {
            get
            {
                return this.iNT_NUMERO_PEDIDOField;
            }
            set
            {
                this.iNT_NUMERO_PEDIDOField = value;
            }
        }

        /// <remarks/>
        public string STR_RESPONSAVEL_PEDIDO
        {
            get
            {
                return this.sTR_RESPONSAVEL_PEDIDOField;
            }
            set
            {
                this.sTR_RESPONSAVEL_PEDIDOField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DAT_ATUALIZACAO
        {
            get
            {
                return this.dAT_ATUALIZACAOField;
            }
            set
            {
                this.dAT_ATUALIZACAOField = value;
            }
        }

        /// <remarks/>
        public byte INT_CODIGO_USUARIO
        {
            get
            {
                return this.iNT_CODIGO_USUARIOField;
            }
            set
            {
                this.iNT_CODIGO_USUARIOField = value;
            }
        }

        /// <remarks/>
        public ulong STR_TELEFONE_PEDIDO
        {
            get
            {
                return this.sTR_TELEFONE_PEDIDOField;
            }
            set
            {
                this.sTR_TELEFONE_PEDIDOField = value;
            }
        }

        /// <remarks/>
        public string STR_LOGRADOURO_ENTREGA_PEDIDO
        {
            get
            {
                return this.sTR_LOGRADOURO_ENTREGA_PEDIDOField;
            }
            set
            {
                this.sTR_LOGRADOURO_ENTREGA_PEDIDOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElement(IsNullable = true)]
        public string STR_ENDERECO_ENTREGA_PEDIDO
        {
            get
            {
                return this.sTR_ENDERECO_ENTREGA_PEDIDOField;
            }
            set
            {
                this.sTR_ENDERECO_ENTREGA_PEDIDOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElement(IsNullable = true)]
        public string STR_NUMERO_ENDERECO_ENTREGA_PEDIDO
        {
            get
            {
                return this.sTR_NUMERO_ENDERECO_ENTREGA_PEDIDOField;
            }
            set
            {
                this.sTR_NUMERO_ENDERECO_ENTREGA_PEDIDOField = value;
            }
        }

        /// <remarks/>
        public string STR_COMPLEMENTO_ENDERECO_ENTREGA_PEDIDO
        {
            get
            {
                return this.sTR_COMPLEMENTO_ENDERECO_ENTREGA_PEDIDOField;
            }
            set
            {
                this.sTR_COMPLEMENTO_ENDERECO_ENTREGA_PEDIDOField = value;
            }
        }

        /// <remarks/>
        public string STR_BAIRRO_ENTREGA_PEDIDO
        {
            get
            {
                return this.sTR_BAIRRO_ENTREGA_PEDIDOField;
            }
            set
            {
                this.sTR_BAIRRO_ENTREGA_PEDIDOField = value;
            }
        }

        /// <remarks/>
        public uint STR_CEP_ENTREGA_PEDIDO
        {
            get
            {
                return this.sTR_CEP_ENTREGA_PEDIDOField;
            }
            set
            {
                this.sTR_CEP_ENTREGA_PEDIDOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElement(IsNullable = true)]
        public string STR_CIDADE_ENTREGA_PEDIDO
        {
            get
            {
                return this.sTR_CIDADE_ENTREGA_PEDIDOField;
            }
            set
            {
                this.sTR_CIDADE_ENTREGA_PEDIDOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElement(IsNullable = true)]
        public string STR_ESTADO_ENTREGA_PEDIDO
        {
            get
            {
                return this.sTR_ESTADO_ENTREGA_PEDIDOField;
            }
            set
            {
                this.sTR_ESTADO_ENTREGA_PEDIDOField = value;
            }
        }

        /// <remarks/>
        public string STR_PAIS_ENTREGA_PEDIDO
        {
            get
            {
                return this.sTR_PAIS_ENTREGA_PEDIDOField;
            }
            set
            {
                this.sTR_PAIS_ENTREGA_PEDIDOField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PEDIDOCLIENTES_INTERNET_PEDIDO
    {

        private byte iNT_CODIGO_MEIO_PAGAMENTOField;

        private string dAT_ENTRADA_PEDIDOField;

        private int sTR_FLAG_PEDIDOField;

        private decimal nUM_VALOR_FINAL_PEDIDOField;

        private byte iNT_NUMERO_PARCELAS_PEDIDOField;

        private PEDIDOCLIENTES_INTERNET_PEDIDOMEIO_PAGTO mEIO_PAGTOField;

        private long iNT_NUMERO_PEDIDOField;

        /// <remarks/>
        public byte INT_CODIGO_MEIO_PAGAMENTO
        {
            get
            {
                return this.iNT_CODIGO_MEIO_PAGAMENTOField;
            }
            set
            {
                this.iNT_CODIGO_MEIO_PAGAMENTOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElement(IsNullable = true)]
        public string DAT_ENTRADA_PEDIDO
        {
            get
            {
                return this.dAT_ENTRADA_PEDIDOField;
            }
            set
            {
                this.dAT_ENTRADA_PEDIDOField = value;
            }
        }

        /// <remarks/>
        public int STR_FLAG_PEDIDO
        {
            get
            {
                return this.sTR_FLAG_PEDIDOField;
            }
            set
            {
                this.sTR_FLAG_PEDIDOField = value;
            }
        }

        /// <remarks/>
        public decimal NUM_VALOR_FINAL_PEDIDO
        {
            get
            {
                return this.nUM_VALOR_FINAL_PEDIDOField;
            }
            set
            {
                this.nUM_VALOR_FINAL_PEDIDOField = value;
            }
        }

        /// <remarks/>
        public byte INT_NUMERO_PARCELAS_PEDIDO
        {
            get
            {
                return this.iNT_NUMERO_PARCELAS_PEDIDOField;
            }
            set
            {
                this.iNT_NUMERO_PARCELAS_PEDIDOField = value;
            }
        }

        /// <remarks/>
        public PEDIDOCLIENTES_INTERNET_PEDIDOMEIO_PAGTO MEIO_PAGTO
        {
            get
            {
                return this.mEIO_PAGTOField;
            }
            set
            {
                this.mEIO_PAGTOField = value;
            }
        }

        /// <remarks/>
        public long INT_NUMERO_PEDIDO
        {
            get
            {
                return this.iNT_NUMERO_PEDIDOField;
            }
            set
            {
                this.iNT_NUMERO_PEDIDOField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PEDIDOCLIENTES_INTERNET_PEDIDOMEIO_PAGTO
    {

        private object[] itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MP_CARTAO_CREDITO", typeof(PEDIDOCLIENTES_INTERNET_PEDIDOMEIO_PAGTOMP_CARTAO_CREDITO))]
        [System.Xml.Serialization.XmlElementAttribute("MP_FINANCIAMENTO", typeof(PEDIDOCLIENTES_INTERNET_PEDIDOMEIO_PAGTOMP_FINANCIAMENTO))]
        public object[] Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PEDIDOCLIENTES_INTERNET_PEDIDOMEIO_PAGTOMP_CARTAO_CREDITO
    {

        private long iNT_NUMERO_PEDIDOField;

        private int iNT_NUMERO_PARCELA_MPField;

        private int iNT_CODIGO_OP_CARTAOField;

        private string sTR_VN_ID_PedidoField;

        private int sTR_VN_Cod_AutorizaField;

        private string sTR_SAFENET_NUMAUTORField;

        private string sTR_SAFENET_NUMCVField;

        private string sTR_SAFENET_NUMAUTENTField;

        private string sTR_NOME_CLIENTE_CARTAOField;

        private string sTR_NUMERO_CARTAO_MPField;

        private string sTR_VENCIMENTO_CARTAO_MPField;

        private int sTR_FLAG_COBRANCAField;

        private decimal nUM_VALOR_PARCELA_PEDIDOField;

        private string dAT_ATUALIZACAOField;

        /// <remarks/>
        public long INT_NUMERO_PEDIDO
        {
            get
            {
                return this.iNT_NUMERO_PEDIDOField;
            }
            set
            {
                this.iNT_NUMERO_PEDIDOField = value;
            }
        }

        /// <remarks/>
        public int INT_NUMERO_PARCELA_MP
        {
            get
            {
                return this.iNT_NUMERO_PARCELA_MPField;
            }
            set
            {
                this.iNT_NUMERO_PARCELA_MPField = value;
            }
        }

        /// <remarks/>
        public int INT_CODIGO_OP_CARTAO
        {
            get
            {
                return this.iNT_CODIGO_OP_CARTAOField;
            }
            set
            {
                this.iNT_CODIGO_OP_CARTAOField = value;
            }
        }

        /// <remarks/>
        public string STR_VN_ID_Pedido
        {
            get
            {
                return this.sTR_VN_ID_PedidoField;
            }
            set
            {
                this.sTR_VN_ID_PedidoField = value;
            }
        }

        /// <remarks/>
        public int STR_VN_Cod_Autoriza
        {
            get
            {
                return this.sTR_VN_Cod_AutorizaField;
            }
            set
            {
                this.sTR_VN_Cod_AutorizaField = value;
            }
        }

        /// <remarks/>
        public string STR_SAFENET_NUMAUTOR
        {
            get
            {
                return this.sTR_SAFENET_NUMAUTORField;
            }
            set
            {
                this.sTR_SAFENET_NUMAUTORField = value;
            }
        }

        /// <remarks/>
        public string STR_SAFENET_NUMCV
        {
            get
            {
                return this.sTR_SAFENET_NUMCVField;
            }
            set
            {
                this.sTR_SAFENET_NUMCVField = value;
            }
        }

        /// <remarks/>
        public string STR_SAFENET_NUMAUTENT
        {
            get
            {
                return this.sTR_SAFENET_NUMAUTENTField;
            }
            set
            {
                this.sTR_SAFENET_NUMAUTENTField = value;
            }
        }

        /// <remarks/>
        public string STR_NOME_CLIENTE_CARTAO
        {
            get
            {
                return this.sTR_NOME_CLIENTE_CARTAOField;
            }
            set
            {
                this.sTR_NOME_CLIENTE_CARTAOField = value;
            }
        }

        /// <remarks/>
        public string STR_NUMERO_CARTAO_MP
        {
            get
            {
                return this.sTR_NUMERO_CARTAO_MPField;
            }
            set
            {
                this.sTR_NUMERO_CARTAO_MPField = value;
            }
        }

        /// <remarks/>
        public string STR_VENCIMENTO_CARTAO_MP
        {
            get
            {
                return this.sTR_VENCIMENTO_CARTAO_MPField;
            }
            set
            {
                this.sTR_VENCIMENTO_CARTAO_MPField = value;
            }
        }

        /// <remarks/>
        public int STR_FLAG_COBRANCA
        {
            get
            {
                return this.sTR_FLAG_COBRANCAField;
            }
            set
            {
                this.sTR_FLAG_COBRANCAField = value;
            }
        }

        /// <remarks/>
        public decimal NUM_VALOR_PARCELA_PEDIDO
        {
            get
            {
                return this.nUM_VALOR_PARCELA_PEDIDOField;
            }
            set
            {
                this.nUM_VALOR_PARCELA_PEDIDOField = value;
            }
        }

        /// <remarks/>
        public string DAT_ATUALIZACAO
        {
            get
            {
                return this.dAT_ATUALIZACAOField;
            }
            set
            {
                this.dAT_ATUALIZACAOField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PEDIDOCLIENTES_INTERNET_PEDIDOMEIO_PAGTOMP_FINANCIAMENTO
    {

        private ulong sTR_NUMERO_CONTRATOField;

        private string sTR_FLAG_COM_ENTRADAField;

        private uint iNT_CONTROLE_ABNField;

        private PEDIDOCLIENTES_INTERNET_PEDIDOMEIO_PAGTOMP_FINANCIAMENTOCONSULTA_ABN cONSULTA_ABNField;

        /// <remarks/>
        public ulong STR_NUMERO_CONTRATO
        {
            get
            {
                return this.sTR_NUMERO_CONTRATOField;
            }
            set
            {
                this.sTR_NUMERO_CONTRATOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public string STR_FLAG_COM_ENTRADA
        {
            get
            {
                return this.sTR_FLAG_COM_ENTRADAField;
            }
            set
            {
                this.sTR_FLAG_COM_ENTRADAField = value;
            }
        }

        /// <remarks/>
        public uint INT_CONTROLE_ABN
        {
            get
            {
                return this.iNT_CONTROLE_ABNField;
            }
            set
            {
                this.iNT_CONTROLE_ABNField = value;
            }
        }
        
        /// <remarks/>
        public PEDIDOCLIENTES_INTERNET_PEDIDOMEIO_PAGTOMP_FINANCIAMENTOCONSULTA_ABN CONSULTA_ABN
        {
            get
            {
                return this.cONSULTA_ABNField;
            }
            set
            {
                this.cONSULTA_ABNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PEDIDOCLIENTES_INTERNET_PEDIDOMEIO_PAGTOMP_FINANCIAMENTOCONSULTA_ABN
    {
        private string sTR_STATUS_CONTRATOField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElement(IsNullable=true)]
        public string STR_STATUS_CONTRATO
        {
            get
            {
                return this.sTR_STATUS_CONTRATOField;
            }
            set
            {
                this.sTR_STATUS_CONTRATOField = value;
            }
        }
    }

    public class MyXmlTextWriter : XmlTextWriter
    {
        private StringWriter _swriter = null;

        public MyXmlTextWriter(StringWriter w) : base(w) { _swriter = w; }
        public override void WriteEndElement()
        {
            base.WriteFullEndElement();
        }
        public override void WriteStartAttribute(string prefix, string localName, string ns)
        {
            base.WriteStartAttribute(null, null, null);
        }
        public override void WriteEndAttribute()
        {
        }
        public override void WriteString(string text)
        {
            if(this.WriteState != WriteState.Attribute)
                base.WriteString(text);
        }
        public string GetXML()
        {
            if (_swriter != null)
                return _swriter.ToString().Replace(" =\"\">", ">");
            else
                return null;
        }
    }
}
